executable   = $ENV(WORK_DIR)/condor/executable_step2.sh
arguments    = $(input_dir) $(output_dir) $(pair)
output       = $ENV(WORK_DIR)/condor/logs/job_$ENV(TAG)_$(ClusterId).$(ProcId).out
error        = $ENV(WORK_DIR)/condor/logs/job_$ENV(TAG)_$(ClusterId).$(ProcId).err
log          = $ENV(WORK_DIR)/condor/logs/job_$ENV(TAG)_$(ClusterId).log
+JobFlavour  = "tomorrow"

getenv = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $ENV(X509_USER_PROXY)
x509userproxy=$ENV(X509_USER_PROXY)
use_x509userproxy = True
JobBatchName = "$ENV(TAG)"


# One line per (input_dir, output_dir) x {ij, jk, ki} -> 3 jobs per directory
queue input_dir,output_dir,pair from (
#/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_{run_start}_{run_stop}/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_{run_start}_{run_stop}/step2  ij
#/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_{run_start}_{run_stop}/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_{run_start}_{run_stop}/step2  jk
#/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_{run_start}_{run_stop}/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_{run_start}_{run_stop}/step2  ki
###
#/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_147644_147885/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_147644_147885/step2  ij
#/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_147644_147885/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_147644_147885/step2  jk
#/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_147644_147885/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_147644_147885/step2  ki
##
/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_149585_149665/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_149585_149665/step2  ij
/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_149585_149665/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_149585_149665/step2  jk
/eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_149585_149665/step1  /eos/user/r/rovitale/repos/tbanalysis-bootstrap/processing/results_149585_149665/step2  ki
)
